Nil RTOS: NilFIFO< Type, Size > Class Template Reference
NilFIFO< Type, Size > Class Template Reference
NilFIFO
Detailed Description
template<typename Type, size_t Size>
class NilFIFO< Type, Size >
A thread safe FIFO.
A FIFO for a single producer/consumer pair.
Definition at line 179 of file NilFIFO.h.
#include <NilFIFO.h>
Public Member Functions
NilFIFO ()
size_t dataCount ()
size_t freeCount ()
void signalData ()
void signalFree ()
Type * waitData (systime_t time)
Type * waitFree (systime_t time)
Constructor & Destructor Documentation
template<typename Type , size_t Size> NilFIFO< Type, Size >::NilFIFO () [inline]
constructor
Definition at line 182 of file NilFIFO.h.
References nilSemInit.
Member Function Documentation
template<typename Type , size_t Size> size_t NilFIFO< Type, Size >::dataCount () [inline]
Returns:
count of data records in the FIFO.
Definition at line 187 of file NilFIFO.h.
References nilSemGetCounter().
template<typename Type , size_t Size> size_t NilFIFO< Type, Size >::freeCount () [inline]
Returns:
count of free records in the FIFO.
Definition at line 190 of file NilFIFO.h.
References nilSemGetCounter().
template<typename Type , size_t Size> void NilFIFO< Type, Size >::signalData () [inline]
Signal that a data record is ready.
Note:
Must only be called in producer thread.
Definition at line 195 of file NilFIFO.h.
References nilSemSignal().
template<typename Type , size_t Size> void NilFIFO< Type, Size >::signalFree () [inline]
Signal that a record is free.
Note:
Must only be called in consumer thread.
Definition at line 201 of file NilFIFO.h.
References nilSemSignal().
template<typename Type , size_t Size> Type* NilFIFO< Type, Size >::waitData (systime_t time) [inline]
Wait for a data record.
Parameters:
[in] time the number of ticks before the operation timeouts, the following special values are allowed:
TIME_IMMEDIATE immediate timeout.
TIME_INFINITE no timeout.
Note:
Must only be called in consumer thread.
Returns:
pointer to the data record or null if no data record is availabile.
Definition at line 215 of file NilFIFO.h.
References NIL_MSG_OK, and nilSemWaitTimeout().
template<typename Type , size_t Size> Type* NilFIFO< Type, Size >::waitFree (systime_t time) [inline]
Wait for a free record.
Parameters:
[in] time the number of ticks before the operation timeouts, the following special values are allowed:
TIME_IMMEDIATE immediate timeout.
TIME_INFINITE no timeout.
Note:
Must only be called in producer thread.
Returns:
pointer to the free record or null if no free record is availabile.
Definition at line 234 of file NilFIFO.h.
References NIL_MSG_OK, and nilSemWaitTimeout().