Nil RTOS: NilStatsFIFO< Type, Size > Class Template Reference
NilStatsFIFO< Type, Size > Class Template Reference
NilFIFO
Detailed Description
template<typename Type, size_t Size>
class NilStatsFIFO< Type, Size >
A thread safe FIFO with statistics.
A FIFO for a single producer/consumer pair with statistics.
Definition at line 40 of file NilFIFO.h.
#include <NilFIFO.h>
Public Member Functions
NilStatsFIFO ()
void countOverrun ()
size_t dataCount ()
size_t freeCount ()
size_t overrunCount ()
size_t maxOverrunCount ()
size_t minimumFreeCount ()
void printStats (Print *pr)
void signalData ()
void signalFree ()
Type * waitData (systime_t time)
Type * waitFree (systime_t time)
Constructor & Destructor Documentation
template<typename Type , size_t Size> NilStatsFIFO< Type, Size >::NilStatsFIFO () [inline]
constructor
Definition at line 43 of file NilFIFO.h.
References nilSemInit.
Member Function Documentation
template<typename Type , size_t Size> void NilStatsFIFO< Type, Size >::countOverrun () [inline]
Increment overrun count
Note:
Must only be called in producer thread.
Definition at line 51 of file NilFIFO.h.
Referenced by NilStatsFIFO< Type, Size >::waitFree().
template<typename Type , size_t Size> size_t NilStatsFIFO< Type, Size >::dataCount () [inline]
Returns:
count of data records in the FIFO.
Definition at line 56 of file NilFIFO.h.
References nilSemGetCounter().
template<typename Type , size_t Size> size_t NilStatsFIFO< Type, Size >::freeCount () [inline]
Returns:
count of free records in the FIFO.
Definition at line 59 of file NilFIFO.h.
References nilSemGetCounter().
Referenced by NilStatsFIFO< Type, Size >::signalFree().
template<typename Type , size_t Size> size_t NilStatsFIFO< Type, Size >::overrunCount () [inline]
Count of overruns since last call to signalData().
Note:
Must only be called in producer thread.
Returns:
overrun count.
Definition at line 67 of file NilFIFO.h.
template<typename Type , size_t Size> size_t NilStatsFIFO< Type, Size >::maxOverrunCount () [inline]
Returns:
maximum overrun count.
Definition at line 70 of file NilFIFO.h.
References nilSysLock, and nilSysUnlock.
template<typename Type , size_t Size> size_t NilStatsFIFO< Type, Size >::minimumFreeCount () [inline]
Returns:
minimum free count.
Definition at line 77 of file NilFIFO.h.
References nilSysLock, and nilSysUnlock.
template<typename Type , size_t Size> void NilStatsFIFO< Type, Size >::printStats (Print * pr) [inline]
Print FIFO statistics.
Parameters:
[in] pr Print stream for the output.
Note:
Must be called when consumer/producer are idle for consistent results.
Definition at line 92 of file NilFIFO.h.
template<typename Type , size_t Size> void NilStatsFIFO< Type, Size >::signalData () [inline]
Signal that a data record is ready.
Note:
Must only be called in producer thread.
Definition at line 108 of file NilFIFO.h.
References nilSemSignal().
template<typename Type , size_t Size> void NilStatsFIFO< Type, Size >::signalFree () [inline]
Signal that a record is free.
Note:
Must only be called in consumer thread.
Definition at line 115 of file NilFIFO.h.
References NilStatsFIFO< Type, Size >::freeCount(), and nilSemSignal().
template<typename Type , size_t Size> Type* NilStatsFIFO< Type, Size >::waitData (systime_t time) [inline]
Wait for a data record.
Parameters:
[in] time the number of ticks before the operation timeouts, the following special values are allowed:
TIME_IMMEDIATE immediate timeout.
TIME_INFINITE no timeout.
Note:
Must only be called in consumer thread.
Returns:
pointer to the data record or null if no data record is availabile.
Definition at line 131 of file NilFIFO.h.
References NIL_MSG_OK, and nilSemWaitTimeout().
template<typename Type , size_t Size> Type* NilStatsFIFO< Type, Size >::waitFree (systime_t time) [inline]
Wait for a free record.
Parameters:
[in] time the number of ticks before the operation timeouts, the following special values are allowed:
TIME_IMMEDIATE immediate timeout.
TIME_INFINITE no timeout.
Note:
Must only be called in producer thread.
Returns:
pointer to the free record or null if no free record is availabile.
Definition at line 150 of file NilFIFO.h.
References NilStatsFIFO< Type, Size >::countOverrun(), NIL_MSG_OK, and nilSemWaitTimeout().