Nil RTOS: TwiMaster Class Reference
TwiMaster Class Reference
TwiMaster
Detailed Description
Two Wire Interface class for I2C master mode.
Definition at line 41 of file TwiMaster.h.
#include <TwiMaster.h>
Public Member Functions
void begin (bool speed=I2C_400KHZ, bool pullups=I2C_NO_PULLUPS)
bool transfer (uint8_t addrRW, void *buf, size_t nbytes, uint8_t option=I2C_STOP)
bool transferContinue (void *buf, size_t nbytes, uint8_t option=I2C_STOP)
void speed (bool speedCode)
void pullups (bool pullupState)
uint8_t failureState ()
void printInfo (Print *pr)
uint8_t currentState ()
bool returnStatus ()
uint8_t requestSize ()
uint8_t bytesTransfered ()
Member Function Documentation
void TwiMaster::begin (bool speed = I2C_400KHZ, bool pullups = I2C_NO_PULLUPS) [inline]
Initialize the AVR 2-wire Serial Interface.
Parameters:
[in] speed I2C bus speed, one of:
I2C_400KHZ
I2C_100KHZ
[in] pullups State of internal AVR pull-ups, one of:
I2C_NO_PULLUPS
I2C_PULLUPS
Definition at line 55 of file TwiMaster.h.
References pullups(), and speed().
bool TwiMaster::transfer (uint8_t addrRW, void * buf, size_t nbytes, uint8_t option = I2C_STOP) [inline]
Start an I2C transfer with possible continuation.
Parameters:
[in] addrRW I2C slave address plus R/W bit. The I2C slave address is in the high seven bits and is ORed with on of the following:
I2C_READ for a read transfer.
I2C_WRITE for a write transfer.
[in,out] buf Source or destination for transfer.
[in] nbytes Number of bytes to transfer (may be zero).
[in] option Option for ending the transfer, one of:
I2C_STOP end the transfer with an I2C stop condition.
I2C_REP_START end the transfer with an I2C repeated start condition.
I2C_CONTINUE allow additional transferContinue() calls.
Returns:
true for success else false.
Definition at line 79 of file TwiMaster.h.
bool TwiMaster::transferContinue (void * buf, size_t nbytes, uint8_t option = I2C_STOP) [inline]
Continue an I2C transfer.
Parameters:
[in,out] buf Source or destination for transfer.
[in] nbytes Number of bytes to transfer (may be zero).
[in] option Option for ending the transfer, one of:
I2C_STOP end the transfer with an I2C stop condition.
I2C_REP_START end the transfer with an I2C repeated start condition.
I2C_CONTINUE allow additional transferContinue() calls.
Returns:
true for success else false.
Definition at line 98 of file TwiMaster.h.
void TwiMaster::speed (bool speedCode) [inline]
Set the I2C bus speed.
Parameters:
[in] speedCode I2C bus speed, one of:
I2C_400KHZ
I2C_100KHZ
Definition at line 109 of file TwiMaster.h.
Referenced by begin().
void TwiMaster::pullups (bool pullupState) [inline]
Enable or disable internal pull-up resistors.
Parameters:
[in] pullupState State of internal AVR pull-ups, one of:
I2C_NO_PULLUPS
I2C_PULLUPS
Definition at line 118 of file TwiMaster.h.
Referenced by begin().
uint8_t TwiMaster::failureState () [inline]
Returns:
The I2C bus state when failue was detected in the last transfer() or transferContinue() call.
Definition at line 124 of file TwiMaster.h.
void TwiMaster::printInfo (Print * pr) [inline]
Print internal information from the last transfer() or transferContinue() call.
Parameters:
[in] pr The print stream for the output.
Definition at line 131 of file TwiMaster.h.
uint8_t TwiMaster::currentState () [inline]
Returns:
The current I2C bus state.
Definition at line 135 of file TwiMaster.h.
bool TwiMaster::returnStatus () [inline]
Returns:
The status returned by the last transfer() or transferContinue() call.
Definition at line 140 of file TwiMaster.h.
uint8_t TwiMaster::requestSize () [inline]
Returns:
The number of bytes of data requested for transfer in the last transfer() or transferContinue() call.
Definition at line 146 of file TwiMaster.h.
uint8_t TwiMaster::bytesTransfered () [inline]
Returns:
The actual number of data bytes transfered in the last transfer() or transferContinue() call.
Definition at line 151 of file TwiMaster.h.