Nil RTOS: Arduino
Arduino
Detailed Description
Arduino Nil RTOS library.
Functions
cnt_t nilSemGetCounter (semaphore_t *sp)
Returns the semaphore counter current value.
size_t nilUnusedStack (uint8_t nt)
size_t nilUnusedHeapIdle ()
bool nilSysBegin ()
bool nilSysBeginNoFill ()
void nilThdDelay (systime_t time)
Delay the invoking thread for the specified time.
void nilThdDelayUntil (systime_t time)
Delay the invoking thread until the system time reaches to the specified value.
void boardInit ()
void nilPrintStackSizes (Print *pr)
void nilPrintUnusedStack (Print *pr)
Defines
#define NIL_RTOS_VERSION 20130719
#define SEMAPHORE_DECL(name, n) semaphore_t name = {n}
Static semaphore initializer.
#define nilThdDelayMilliseconds(msec) nilThdDelay(MS2ST(msec))
Delays the invoking thread for the specified number of milliseconds.
#define nilSemFastWaitI(sp) ((sp)->cnt--)
Decreases the semaphore counter.
#define nilSemFastSignalI(sp) ((sp)->cnt++)
Increases the semaphore counter.
#define nilSemGetCounterI(sp) ((sp)->cnt)
Returns the semaphore counter current value.
#define nilIsIdleThread() (nil.current == nil.idlep)
Returns true if current thread is the idle thread.
Function Documentation
cnt_t nilSemGetCounter (semaphore_t * sp)
Returns the semaphore counter current value.
Parameters:
[in] sp pointer to a Semaphore structure.
Returns:
the value of the semaphore counter.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 42 of file NilRTOS.c.
References semaphore_t::cnt, nilSysLock, and nilSysUnlock.
Referenced by NilFIFO< Type, Size >::dataCount(), NilStatsFIFO< Type, Size >::dataCount(), NilFIFO< Type, Size >::freeCount(), and NilStatsFIFO< Type, Size >::freeCount().
size_t nilUnusedStack (uint8_t nt)
Determine unused stack for a thread.
Parameters:
[in] nt Task index.
Returns:
Number of unused stack bytes.
Definition at line 56 of file NilRTOS.c.
References nil_thread_cfg::size, and nil_thread_cfg::wap.
size_t nilUnusedHeapIdle ()
Determine unused bytes in the heap and idle yhread stack area.
Returns:
Number of unused bytes.
Definition at line 66 of file NilRTOS.c.
bool nilSysBegin ()
Start Nil RTOS with all stack memory initialized to a known value.
Returns:
TRUE for success else FALSE.
Definition at line 86 of file NilRTOS.c.
References nilSysBeginNoFill().
bool nilSysBeginNoFill ()
Start Nil RTOS with raw uninitialized stack memory. This call saves a little flash compared to nilSysBegin().
Returns:
TRUE for success else FALSE.
Definition at line 96 of file NilRTOS.c.
References boardInit(), FALSE, nilSysInit(), nilSysLock, and TRUE.
Referenced by nilSysBegin().
void nilThdDelay (systime_t time)
Delay the invoking thread for the specified time.
Parameters:
[in] time the delay in system ticks.
Note:
This function does not sleep and will block all lower priority threads. This function should only be used in the idle thread.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 114 of file NilRTOS.c.
References nilTimeNow().
Referenced by nilThdDelayUntil().
void nilThdDelayUntil (systime_t time)
Delay the invoking thread until the system time reaches to the specified value.
Parameters:
[in] time absolute system time
Note:
This function does not sleep and will block all lower priority threads. This function should only be used in the idle thread.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 131 of file NilRTOS.c.
References nilThdDelay(), and nilTimeNow().
void boardInit (void)
Board-specific initialization code for Arduino. Use timer 0 compare A to geneate an interrupt every 1024 usec.
Definition at line 49 of file board.c.
Referenced by nilSysBeginNoFill().
void nilPrintStackSizes (Print * pr)
Print size of all all stacks.
Parameters:
[in] pr Print stream for output.
Definition at line 34 of file nilUtility.cpp.
References nil_thread_cfg::size, and nil_thread_cfg::wap.
void nilPrintUnusedStack (Print * pr)
Print unused byte count for all stacks.
Parameters:
[in] pr Print stream for output.
Definition at line 48 of file nilUtility.cpp.
References nil_thread_cfg::size, and nil_thread_cfg::wap.
Define Documentation
#define NIL_RTOS_VERSION 20130719
NilRTOS version YYYYMMDD
Definition at line 34 of file NilRTOS.h.
#define SEMAPHORE_DECL (name, n) semaphore_t name = {n}
Static semaphore initializer.
Statically initialized semaphores require no explicit initialization using nilSemInit().
Parameters:
[in] name the name of the semaphore variable
[in] n the counter initial value, this value must be non-negative
Definition at line 49 of file NilRTOS.h.
#define nilThdDelayMilliseconds (msec) nilThdDelay(MS2ST(msec))
Delays the invoking thread for the specified number of milliseconds.
Note:
This function does not sleep and will block all lower priority threads. This function should only be used in the idle thread.
The specified time is rounded up to a value allowed by the real system clock.
The maximum specified value is implementation dependent.
Parameters:
[in] msec time in milliseconds, must be different from zero
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 65 of file NilRTOS.h.
#define nilSemFastWaitI (sp) ((sp)->cnt--)
Decreases the semaphore counter.
This macro can be used when the counter is known to be positive.
Function Class:
This is an I-Class API, this function can be invoked from within a system lock zone by both threads and interrupt handlers.
Definition at line 73 of file NilRTOS.h.
#define nilSemFastSignalI (sp) ((sp)->cnt++)
Increases the semaphore counter.
This macro can be used when the counter is known to be not negative.
Function Class:
This is an I-Class API, this function can be invoked from within a system lock zone by both threads and interrupt handlers.
Definition at line 82 of file NilRTOS.h.
#define nilSemGetCounterI (sp) ((sp)->cnt)
Returns the semaphore counter current value.
Function Class:
This is an I-Class API, this function can be invoked from within a system lock zone by both threads and interrupt handlers.
Definition at line 89 of file NilRTOS.h.
#define nilIsIdleThread () (nil.current == nil.idlep)
Returns true if current thread is the idle thread.
Definition at line 93 of file NilRTOS.h.
Referenced by nilAnalogRead(), and nilTimer1Wait().