Nil RTOS: Nil
Nil
Detailed Description
Nil RTOS services.
Data Structures
struct semaphore_t
Type of a structure representing a counting semaphore.
struct nil_thread_cfg
Structure representing a thread static configuration.
struct nil_thread
Structure representing a thread.
struct nil_system_t
System data structure.
Functions
void nilSysInit (void)
Initializes the kernel.
void nilSysTimerHandlerI (void)
Time management handler.
thread_ref_t nilSchReadyI (thread_ref_t tr, msg_t msg)
Makes the specified thread ready for execution.
void nilSchRescheduleS ()
Reschedules.
msg_t nilSchGoSleepTimeoutS (tstate_t newstate, systime_t timeout)
Puts the current thread to sleep into the specified state with timeout specification.
msg_t nilThdSuspendTimeoutS (thread_ref_t *trp, systime_t timeout)
Sends the current thread sleeping and sets a reference variable.
void nilThdResumeI (thread_ref_t *trp, msg_t msg)
Wakes up a thread waiting on a thread reference object.
void nilThdSleep (systime_t time)
Suspends the invoking thread for the specified time.
void nilThdSleepUntil (systime_t time)
Suspends the invoking thread until the system time arrives to the specified value.
systime_t nilTimeNow (void)
Current system time.
bool nilTimeNowIsWithin (systime_t start, systime_t end)
Checks if the current system time is within the specified time window.
msg_t nilSemWaitTimeout (semaphore_t *sp, systime_t timeout)
Performs a wait operation on a semaphore with timeout specification.
msg_t nilSemWaitTimeoutS (semaphore_t *sp, systime_t timeout)
Performs a wait operation on a semaphore with timeout specification.
void nilSemSignal (semaphore_t *sp)
Performs a signal operation on a semaphore.
void nilSemSignalI (semaphore_t *sp)
Performs a signal operation on a semaphore.
void nilSemReset (semaphore_t *sp, cnt_t n)
Performs a reset operation on the semaphore.
void nilSemResetI (semaphore_t *sp, cnt_t n)
Performs a reset operation on the semaphore.
Variables
nil_system_t nil
System variables.
Nil RTOS identification
#define _NIL_
Nil RTOS identification.
#define NIL_KERNEL_VERSION "0.0.1"
Kernel version string.
#define NIL_KERNEL_MAJOR 0
Version major number.
#define NIL_KERNEL_MINOR 0
Version minor number.
#define NIL_KERNEL_PATCH 1
Version patch number.
Common constants
#define FALSE 0
Generic 'false' boolean constant.
#define TRUE !FALSE
Generic 'true' boolean constant.
Wakeup status codes
#define NIL_MSG_OK 0
Normal wakeup message.
#define NIL_MSG_TMO -1
Wake-up caused by a timeout condition.
#define NIL_MSG_RST -2
Wake-up caused by a reset condition.
Special time constants
#define TIME_IMMEDIATE ((systime_t)-1)
Zero time specification for some functions with a timeout specification.
#define TIME_INFINITE ((systime_t)0)
Infinite time specification for all functions with a timeout specification.
Thread state related macros
#define NIL_THD_READY 0
Thread ready or executing.
#define NIL_THD_SLEEPING 1
Thread sleeping.
#define NIL_THD_SUSP 2
Thread suspended.
#define NIL_THD_WTSEM 3
Thread waiting on semaphore.
#define NIL_THD_IS_READY(tr) ((tr)->state == NIL_THD_READY)
#define NIL_THD_IS_SLEEPING(tr) ((tr)->state == NIL_THD_SLEEPING)
#define NIL_THD_IS_SUSP(tr) ((tr)->state == NIL_THD_SUSP)
#define NIL_THD_IS_WTSEM(tr) ((tr)->state == NIL_THD_WTSEM)
Threads tables definition macros
#define NIL_THREADS_TABLE_BEGIN() const thread_config_t nil_thd_configs[] = {
Start of user threads table.
#define NIL_THREADS_TABLE_ENTRY(name, funcp, arg, wap, size) {name, funcp, arg, wap, size},
Entry of user threads table.
#define NIL_THREADS_TABLE_END()
End of user threads table.
Macro Functions
#define nilSysHalt() port_halt()
System halt state.
#define nilSysDisable() port_disable()
Enters the kernel lock mode.
#define nilSysEnable() port_enable()
Enters the kernel lock mode.
#define nilSysLock() port_lock()
Enters the kernel lock mode.
#define nilSysUnlock() port_unlock()
Leaves the kernel lock mode.
#define nilSysLockFromISR() port_lock_from_isr()
Enters the kernel lock mode from within an interrupt handler.
#define nilSysUnlockFromISR() port_unlock_from_isr()
Leaves the kernel lock mode from within an interrupt handler.
#define nilThdSleepSeconds(sec) nilThdSleep(S2ST(sec))
Delays the invoking thread for the specified number of seconds.
#define nilThdSleepMilliseconds(msec) nilThdSleep(MS2ST(msec))
Delays the invoking thread for the specified number of milliseconds.
#define nilThdSleepMicroseconds(usec) nilThdSleep(US2ST(usec))
Delays the invoking thread for the specified number of microseconds.
#define nilThdSleepS(timeout) nilSchGoSleepTimeoutS(NIL_THD_SLEEPING, timeout)
Suspends the invoking thread for the specified time.
#define nilThdSleepUntilS(time) nilSchGoSleepTimeoutS(NIL_THD_SLEEPING, (time) - nilTimeNowI())
Suspends the invoking thread until the system time arrives to the specified value.
#define nilSemInit(sp, n) ((sp)->cnt = n)
Initializes a semaphore with the specified counter value.
#define nilSemWait(sp) nilSemWaitTimeout(sp, TIME_INFINITE)
Performs a wait operation on a semaphore.
#define nilSemWaitS(sp) nilSemWaitTimeoutS(sp, TIME_INFINITE)
Performs a wait operation on a semaphore.
#define nilTimeNowI() (nil.systime)
Current system time.
#define nilTimeIsWithin(time, start, end)
Checks if the specified time is within the specified time window.
Threads abstraction macros
#define NIL_THREAD(tname, arg) PORT_THREAD(tname, arg)
Thread declaration macro.
#define nilDbgAssert(c, m, r)
Condition assertion.
ISRs abstraction macros
#define NIL_IRQ_PROLOGUE() PORT_IRQ_PROLOGUE()
IRQ handler enter code.
#define NIL_IRQ_EPILOGUE() PORT_IRQ_EPILOGUE()
IRQ handler exit code.
#define NIL_IRQ_HANDLER(id) PORT_IRQ_HANDLER(id)
Standard normal IRQ handler declaration.
Fast ISRs abstraction macros
#define NIL_FAST_IRQ_HANDLER(id) PORT_FAST_IRQ_HANDLER(id)
Standard fast IRQ handler declaration.
Time conversion utilities
#define S2ST(sec) ((systime_t)((sec) * NIL_CFG_FREQUENCY))
Seconds to system ticks.
#define MS2ST(msec)
Milliseconds to system ticks.
#define US2ST(usec)
Microseconds to system ticks.
Defines
#define NIL_CFG_FREQUENCY 100
System timer resolution in Hz.
#define NIL_CFG_TIMEDELTA 0
Time delta constant for the tick-less mode.
#define NIL_CFG_ENABLE_ASSERTS FALSE
System assertions.
#define NIL_CFG_THREAD_EXT_FIELDS
Threads descriptor structure extension.
#define NIL_DBG_ENABLED TRUE
Typedefs
typedef struct port_intctx intctx_t
Type of internal context structure.
typedef void(* tfunc_t)(void *)
Thread function.
typedef struct nil_thread_cfg thread_config_t
Type of a structure representing a thread static configuration.
typedef struct nil_thread thread_t
Type of a structure representing a thread.
typedef thread_t * thread_ref_t
Type of a thread reference.
Function Documentation
void nilSysInit (void)
Initializes the kernel.
Initializes the kernel structures, the current instructions flow becomes the idle thread upon return. The idle thread must not invoke any kernel primitive able to change state to not runnable.
Function Class:
Special function, this function has special requirements see the notes.
Definition at line 67 of file nil.c.
References nil_thread_cfg::arg, nil_system_t::current, nil_thread_cfg::funcp, nil_system_t::idlep, nil_system_t::next, NIL_CFG_NUM_THREADS, NIL_CFG_THREAD_EXT_INIT_HOOK, NIL_THD_READY, nilSysEnable, port_init, port_switch, SETUP_CONTEXT, nil_thread_cfg::size, nil_thread::state, nil_system_t::threads, nil_thread::timeout, nil_thread_cfg::wap, and WHG_MOD.
Referenced by nilSysBeginNoFill().
void nilSysTimerHandlerI (void)
Time management handler.
Note:
This handler has to be invoked by a periodic ISR in order to reschedule the waiting threads.
Function Class:
This is an I-Class API, this function can be invoked from within a system lock zone by both threads and interrupt handlers.
Definition at line 114 of file nil.c.
References semaphore_t::cnt, nil_system_t::idlep, NIL_MSG_TMO, nilDbgAssert, nilSchReadyI(), nilSysLockFromISR, nilSysUnlockFromISR, nil_thread::semp, nil_system_t::systime, nil_system_t::threads, nil_thread::timeout, and nil_thread::trp.
Referenced by NIL_IRQ_HANDLER().
thread_ref_t nilSchReadyI (thread_ref_t tr, msg_t msg)
Makes the specified thread ready for execution.
Parameters:
[in] tr reference to the thread_t object
[in] msg the wakeup message
Returns:
The same reference passed as parameter.
Definition at line 209 of file nil.c.
References nil_system_t::current, nil_system_t::idlep, nil_thread::msg, nil_system_t::next, NIL_CFG_NUM_THREADS, NIL_THD_READY, nilDbgAssert, nil_thread::state, nil_system_t::threads, nil_thread::timeout, and WHG_MOD.
Referenced by nilSemResetI(), nilSemSignalI(), nilSysTimerHandlerI(), and nilThdResumeI().
void nilSchRescheduleS ()
Reschedules.
Function Class:
This is an S-Class API, this function can be invoked from within a system lock zone by threads only.
Definition at line 236 of file nil.c.
References nil_system_t::current, nil_system_t::idlep, nil_system_t::next, NIL_CFG_IDLE_LEAVE_HOOK, NIL_CFG_NUM_THREADS, port_switch, and nil_system_t::threads.
Referenced by nilSemReset(), and nilSemSignal().
msg_t nilSchGoSleepTimeoutS (tstate_t newstate, systime_t timeout)
Puts the current thread to sleep into the specified state with timeout specification.
The thread goes into a sleeping state, if it is not awakened explicitly within the specified system time then it is forcibly awakened with a NIL_MSG_TMO low level message.
Parameters:
[in] newstate the new thread state or a semaphore pointer
[in] timeout the number of ticks before the operation timeouts. the following special values are allowed:
TIME_INFINITE no timeout.
Returns:
The wakeup message.
Return values:
NIL_MSG_TMO if a timeout occurred.
Function Class:
This is an S-Class API, this function can be invoked from within a system lock zone by threads only.
Definition at line 272 of file nil.c.
References nil_system_t::current, nil_system_t::idlep, nil_system_t::lasttime, nil_thread::msg, nil_system_t::next, nil_system_t::nexttime, NIL_CFG_IDLE_ENTER_HOOK, NIL_CFG_NUM_THREADS, NIL_CFG_TIMEDELTA, nilDbgAssert, nilTimeIsWithin, nilTimeNowI, port_switch, nil_thread::state, nil_system_t::threads, TIME_INFINITE, and nil_thread::timeout.
Referenced by nilSemWaitTimeoutS(), and nilThdSuspendTimeoutS().
msg_t nilThdSuspendTimeoutS (thread_ref_t * trp, systime_t timeout)
Sends the current thread sleeping and sets a reference variable.
Note:
This function must reschedule, it can only be called from thread context.
Parameters:
[in] trp a pointer to a thread reference object
[in] timeout the number of ticks before the operation timeouts, the following special values are allowed:
TIME_INFINITE no timeout.
Returns:
The wake up message.
Function Class:
This is an S-Class API, this function can be invoked from within a system lock zone by threads only.
Definition at line 355 of file nil.c.
References nil_system_t::current, NIL_THD_SUSP, nilDbgAssert, nilSchGoSleepTimeoutS(), and nil_thread::trp.
void nilThdResumeI (thread_ref_t * trp, msg_t msg)
Wakes up a thread waiting on a thread reference object.
Note:
This function must not reschedule because it can be called from ISR context.
Parameters:
[in] trp a pointer to a thread reference object
[in] msg the message code
Function Class:
This is an I-Class API, this function can be invoked from within a system lock zone by both threads and interrupt handlers.
Definition at line 374 of file nil.c.
References nilDbgAssert, and nilSchReadyI().
void nilThdSleep (systime_t time)
Suspends the invoking thread for the specified time.
Parameters:
[in] time the delay in system ticks
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 393 of file nil.c.
References nilSysLock, nilSysUnlock, and nilThdSleepS.
void nilThdSleepUntil (systime_t time)
Suspends the invoking thread until the system time arrives to the specified value.
Parameters:
[in] time absolute system time
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 408 of file nil.c.
References nilSysLock, nilSysUnlock, and nilThdSleepUntilS.
systime_t nilTimeNow (void)
Current system time.
Returns the number of system ticks since the nilSysInit() invocation.
Note:
The counter can reach its maximum and then restart from zero.
This function is designed to work with the nilThdSleepUntil().
Returns:
The system time in ticks.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 426 of file nil.c.
References nilSysLock, nilSysUnlock, and nilTimeNowI.
Referenced by nilThdDelay(), nilThdDelayUntil(), and nilTimeNowIsWithin().
bool nilTimeNowIsWithin (systime_t start, systime_t end)
Checks if the current system time is within the specified time window.
Note:
When start==end then the function returns always true because the whole time range is specified.
Parameters:
[in] start the start of the time window (inclusive)
[in] end the end of the time window (non inclusive)
Return values:
true current time within the specified time window.
false current time not within the specified time window.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 449 of file nil.c.
References nilTimeIsWithin, and nilTimeNow().
msg_t nilSemWaitTimeout (semaphore_t * sp, systime_t timeout)
Performs a wait operation on a semaphore with timeout specification.
Parameters:
[in] sp pointer to a semaphore_t structure
[in] timeout the number of ticks before the operation timeouts, the following special values are allowed:
TIME_IMMEDIATE immediate timeout.
TIME_INFINITE no timeout.
Returns:
A message specifying how the invoking thread has been released from the semaphore.
Return values:
NIL_MSG_OK if the thread has not stopped on the semaphore or the semaphore has been signaled.
NIL_MSG_RST if the semaphore has been reset using nilSemReset().
NIL_MSG_TMO if the semaphore has not been signaled or reset within the specified timeout.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 474 of file nil.c.
References nilSemWaitTimeoutS(), nilSysLock, and nilSysUnlock.
Referenced by nilTimer1Wait(), NilFIFO< Type, Size >::waitData(), NilStatsFIFO< Type, Size >::waitData(), NilFIFO< Type, Size >::waitFree(), and NilStatsFIFO< Type, Size >::waitFree().
msg_t nilSemWaitTimeoutS (semaphore_t * sp, systime_t timeout)
Performs a wait operation on a semaphore with timeout specification.
Parameters:
[in] sp pointer to a semaphore_t structure
[in] timeout the number of ticks before the operation timeouts, the following special values are allowed:
TIME_IMMEDIATE immediate timeout.
TIME_INFINITE no timeout.
Returns:
A message specifying how the invoking thread has been released from the semaphore.
Return values:
NIL_MSG_OK if the thread has not stopped on the semaphore or the semaphore has been signaled.
NIL_MSG_RST if the semaphore has been reset using nilSemReset().
NIL_MSG_TMO if the semaphore has not been signaled or reset within the specified timeout.
Function Class:
This is an S-Class API, this function can be invoked from within a system lock zone by threads only.
Definition at line 502 of file nil.c.
References semaphore_t::cnt, nil_system_t::current, NIL_MSG_OK, NIL_MSG_TMO, NIL_THD_WTSEM, nilSchGoSleepTimeoutS(), nil_thread::semp, and TIME_IMMEDIATE.
Referenced by nilSemWaitTimeout().
void nilSemSignal (semaphore_t * sp)
Performs a signal operation on a semaphore.
Postcondition:
This function does not reschedule so a call to a rescheduling function must be performed before unlocking the kernel. Note that interrupt handlers always reschedule on exit so an explicit reschedule must not be performed in ISRs.
Parameters:
[in] sp pointer to a semaphore_t structure
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 529 of file nil.c.
References nilSchRescheduleS(), nilSemSignalI(), nilSysLock, and nilSysUnlock.
Referenced by NilFIFO< Type, Size >::signalData(), NilStatsFIFO< Type, Size >::signalData(), NilFIFO< Type, Size >::signalFree(), and NilStatsFIFO< Type, Size >::signalFree().
void nilSemSignalI (semaphore_t * sp)
Performs a signal operation on a semaphore.
Postcondition:
This function does not reschedule so a call to a rescheduling function must be performed before unlocking the kernel. Note that interrupt handlers always reschedule on exit so an explicit reschedule must not be performed in ISRs.
Parameters:
[in] sp pointer to a semaphore_t structure
Function Class:
This is an I-Class API, this function can be invoked from within a system lock zone by both threads and interrupt handlers.
Definition at line 548 of file nil.c.
References semaphore_t::cnt, NIL_MSG_OK, nilDbgAssert, nilSchReadyI(), nil_thread::semp, and nil_system_t::threads.
Referenced by nilSemSignal().
void nilSemReset (semaphore_t * sp, cnt_t n)
Performs a reset operation on the semaphore.
Postcondition:
After invoking this function all the threads waiting on the semaphore, if any, are released and the semaphore counter is set to the specified, non negative, value.
This function does not reschedule so a call to a rescheduling function must be performed before unlocking the kernel. Note that interrupt handlers always reschedule on exit so an explicit reschedule must not be performed in ISRs.
Parameters:
[in] sp pointer to a semaphore_t structure
[in] n the new value of the semaphore counter. The value must be non-negative.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 583 of file nil.c.
References nilSchRescheduleS(), nilSemResetI(), nilSysLock, and nilSysUnlock.
void nilSemResetI (semaphore_t * sp, cnt_t n)
Performs a reset operation on the semaphore.
Postcondition:
After invoking this function all the threads waiting on the semaphore, if any, are released and the semaphore counter is set to the specified, non negative, value.
This function does not reschedule so a call to a rescheduling function must be performed before unlocking the kernel. Note that interrupt handlers always reschedule on exit so an explicit reschedule must not be performed in ISRs.
Parameters:
[in] sp pointer to a semaphore_t structure
[in] n the new value of the semaphore counter. The value must be non-negative.
Function Class:
This is an I-Class API, this function can be invoked from within a system lock zone by both threads and interrupt handlers.
Definition at line 607 of file nil.c.
References semaphore_t::cnt, NIL_MSG_RST, nilDbgAssert, nilSchReadyI(), nil_thread::semp, and nil_system_t::threads.
Referenced by nilSemReset().
Variable Documentation
nil_system_t nil
System variables.
Definition at line 42 of file nil.c.
Define Documentation
#define _NIL_
Nil RTOS identification.
Definition at line 44 of file nil.h.
#define NIL_KERNEL_VERSION "0.0.1"
Kernel version string.
Definition at line 46 of file nil.h.
#define NIL_KERNEL_MAJOR 0
Version major number.
Definition at line 48 of file nil.h.
#define NIL_KERNEL_MINOR 0
Version minor number.
Definition at line 49 of file nil.h.
#define NIL_KERNEL_PATCH 1
Version patch number.
Definition at line 50 of file nil.h.
#define FALSE 0
Generic 'false' boolean constant.
Definition at line 60 of file nil.h.
Referenced by nilSysBeginNoFill().
#define TRUE !FALSE
Generic 'true' boolean constant.
Definition at line 67 of file nil.h.
Referenced by nilSysBeginNoFill().
#define NIL_MSG_OK 0
Normal wakeup message.
Definition at line 75 of file nil.h.
Referenced by nilSemSignalI(), nilSemWaitTimeoutS(), NilFIFO< Type, Size >::waitData(), NilStatsFIFO< Type, Size >::waitData(), NilFIFO< Type, Size >::waitFree(), and NilStatsFIFO< Type, Size >::waitFree().
#define NIL_MSG_TMO -1
Wake-up caused by a timeout condition.
Definition at line 76 of file nil.h.
Referenced by nilSemWaitTimeoutS(), nilSysTimerHandlerI(), and nilTimer1Wait().
#define NIL_MSG_RST -2
Wake-up caused by a reset condition.
Definition at line 78 of file nil.h.
Referenced by nilSemResetI().
#define TIME_IMMEDIATE ((systime_t)-1)
Zero time specification for some functions with a timeout specification.
Note:
Not all functions accept TIME_IMMEDIATE as timeout parameter, see the specific function documentation.
Definition at line 92 of file nil.h.
Referenced by nilSemWaitTimeoutS(), and nilTimer1Wait().
#define TIME_INFINITE ((systime_t)0)
Infinite time specification for all functions with a timeout specification.
Definition at line 98 of file nil.h.
Referenced by nilSchGoSleepTimeoutS().
#define NIL_THD_READY 0
Thread ready or executing.
Definition at line 105 of file nil.h.
Referenced by nilSchReadyI(), and nilSysInit().
#define NIL_THD_SLEEPING 1
Thread sleeping.
Definition at line 106 of file nil.h.
#define NIL_THD_SUSP 2
Thread suspended.
Definition at line 107 of file nil.h.
Referenced by nilThdSuspendTimeoutS().
#define NIL_THD_WTSEM 3
Thread waiting on semaphore.
Definition at line 108 of file nil.h.
Referenced by nilSemWaitTimeoutS().
#define NIL_CFG_FREQUENCY 100
System timer resolution in Hz.
Definition at line 134 of file nil.h.
#define NIL_CFG_TIMEDELTA 0
Time delta constant for the tick-less mode.
Note:
If this value is zero then the system uses the classic periodic tick. This value represents the minimum number of ticks that is safe to specify in a timeout directive. The value one is not valid, timeouts are rounded up to this value.
Definition at line 146 of file nil.h.
Referenced by nilSchGoSleepTimeoutS().
#define NIL_CFG_ENABLE_ASSERTS FALSE
System assertions.
Definition at line 153 of file nil.h.
#define NIL_CFG_THREAD_EXT_FIELDS
Threads descriptor structure extension.
User fields added to the end of the thread_t structure.
Definition at line 161 of file nil.h.
#define NIL_DBG_ENABLED TRUE
enable debuging
Definition at line 189 of file nil.h.
#define NIL_THREADS_TABLE_BEGIN () const thread_config_t nil_thd_configs[] = {
Start of user threads table.
Definition at line 331 of file nil.h.
#define NIL_THREADS_TABLE_ENTRY (name, funcp, arg, wap, size) {name, funcp, arg, wap, size},
Entry of user threads table.
Definition at line 340 of file nil.h.
#define NIL_THREADS_TABLE_END ()
Value:
{"idle", 0, NULL, NULL, 0}                                                \
};                                                                          \
static thread_t nil_threads[sizeof(nil_thd_configs)/sizeof(thread_config_t)];  \
nil_system_t nil = {0, 0, 0, nil_threads,                                      \
&nil_threads[sizeof(nil_thd_configs)/sizeof(thread_config_t) - 1]};            \
const uint8_t nil_thd_count = sizeof(nil_thd_configs)/sizeof(thread_config_t) - 1;
End of user threads table.
Definition at line 347 of file nil.h.
#define nilSysHalt () port_halt()
System halt state.
Definition at line 368 of file nil.h.
#define nilSysDisable () port_disable()
Enters the kernel lock mode.
Function Class:
Special function, this function has special requirements see the notes.
Definition at line 375 of file nil.h.
#define nilSysEnable () port_enable()
Enters the kernel lock mode.
Function Class:
Special function, this function has special requirements see the notes.
Definition at line 382 of file nil.h.
Referenced by nilSysInit().
#define nilSysLock () port_lock()
Enters the kernel lock mode.
Function Class:
Special function, this function has special requirements see the notes.
Definition at line 389 of file nil.h.
Referenced by NilStatsFIFO< Type, Size >::maxOverrunCount(), NilStatsFIFO< Type, Size >::minimumFreeCount(), nilSemGetCounter(), nilSemReset(), nilSemSignal(), nilSemWaitTimeout(), nilSysBeginNoFill(), nilThdSleep(), nilThdSleepUntil(), nilTimeNow(), and nilTimer1Start().
#define nilSysUnlock () port_unlock()
Leaves the kernel lock mode.
Function Class:
Special function, this function has special requirements see the notes.
Definition at line 396 of file nil.h.
Referenced by _port_thread_start(), NilStatsFIFO< Type, Size >::maxOverrunCount(), NilStatsFIFO< Type, Size >::minimumFreeCount(), nilSemGetCounter(), nilSemReset(), nilSemSignal(), nilSemWaitTimeout(), nilThdSleep(), nilThdSleepUntil(), nilTimeNow(), and nilTimer1Start().
#define nilSysLockFromISR () port_lock_from_isr()
Enters the kernel lock mode from within an interrupt handler.
Note:
This API may do nothing on some architectures, it is required because on ports that support preemptable interrupt handlers it is required to raise the interrupt mask to the same level of the system mutual exclusion zone.
It is good practice to invoke this API before invoking any I-class syscall from an interrupt handler.
This API must be invoked exclusively from interrupt handlers.
Function Class:
Special function, this function has special requirements see the notes.
Definition at line 410 of file nil.h.
Referenced by nilSysTimerHandlerI().
#define nilSysUnlockFromISR () port_unlock_from_isr()
Leaves the kernel lock mode from within an interrupt handler.
Note:
This API may do nothing on some architectures, it is required because on ports that support preemptable interrupt handlers it is required to raise the interrupt mask to the same level of the system mutual exclusion zone.
It is good practice to invoke this API after invoking any I-class syscall from an interrupt handler.
This API must be invoked exclusively from interrupt handlers.
Function Class:
Special function, this function has special requirements see the notes.
Definition at line 425 of file nil.h.
Referenced by nilSysTimerHandlerI().
#define nilThdSleepSeconds (sec) nilThdSleep(S2ST(sec))
Delays the invoking thread for the specified number of seconds.
Note:
The specified time is rounded up to a value allowed by the real system clock.
The maximum specified value is implementation dependent.
Parameters:
[in] sec time in seconds, must be different from zero
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 437 of file nil.h.
#define nilThdSleepMilliseconds (msec) nilThdSleep(MS2ST(msec))
Delays the invoking thread for the specified number of milliseconds.
Note:
The specified time is rounded up to a value allowed by the real system clock.
The maximum specified value is implementation dependent.
Parameters:
[in] msec time in milliseconds, must be different from zero
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 450 of file nil.h.
#define nilThdSleepMicroseconds (usec) nilThdSleep(US2ST(usec))
Delays the invoking thread for the specified number of microseconds.
Note:
The specified time is rounded up to a value allowed by the real system clock.
The maximum specified value is implementation dependent.
Parameters:
[in] usec time in microseconds, must be different from zero
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 463 of file nil.h.
#define nilThdSleepS (timeout) nilSchGoSleepTimeoutS(NIL_THD_SLEEPING, timeout)
Suspends the invoking thread for the specified time.
Parameters:
[in] timeout the delay in system ticks
Function Class:
This is an S-Class API, this function can be invoked from within a system lock zone by threads only.
Definition at line 472 of file nil.h.
Referenced by nilThdSleep().
#define nilThdSleepUntilS (time) nilSchGoSleepTimeoutS(NIL_THD_SLEEPING, (time) - nilTimeNowI())
Suspends the invoking thread until the system time arrives to the specified value.
Parameters:
[in] time absolute system time
Function Class:
This is an S-Class API, this function can be invoked from within a system lock zone by threads only.
Definition at line 483 of file nil.h.
Referenced by nilThdSleepUntil().
#define nilSemInit (sp, n) ((sp)->cnt = n)
Initializes a semaphore with the specified counter value.
Parameters:
[out] sp pointer to a semaphore_t structure
[in] n initial value of the semaphore counter. Must be non-negative.
Function Class:
Initializer, this function just initializes an object and can be invoked before the kernel is initialized.
Definition at line 498 of file nil.h.
Referenced by NilFIFO< Type, Size >::NilFIFO(), and NilStatsFIFO< Type, Size >::NilStatsFIFO().
#define nilSemWait (sp) nilSemWaitTimeout(sp, TIME_INFINITE)
Performs a wait operation on a semaphore.
Parameters:
[in] sp pointer to a semaphore_t structure
Returns:
A message specifying how the invoking thread has been released from the semaphore.
Return values:
NIL_MSG_OK if the thread has not stopped on the semaphore or the semaphore has been signaled.
NIL_MSG_RST if the semaphore has been reset using nilSemReset().
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 512 of file nil.h.
Referenced by nilAnalogRead(), and nilTimer1Wait().
#define nilSemWaitS (sp) nilSemWaitTimeoutS(sp, TIME_INFINITE)
Performs a wait operation on a semaphore.
Parameters:
[in] sp pointer to a semaphore_t structure
Returns:
A message specifying how the invoking thread has been released from the semaphore.
Return values:
NIL_MSG_OK if the thread has not stopped on the semaphore or the semaphore has been signaled.
NIL_MSG_RST if the semaphore has been reset using nilSemReset().
Function Class:
This is an S-Class API, this function can be invoked from within a system lock zone by threads only.
Definition at line 526 of file nil.h.
#define nilTimeNowI () (nil.systime)
Current system time.
Returns the number of system ticks since the nilSysInit() invocation.
Note:
The counter can reach its maximum and then restart from zero.
This function is designed to work with the nilThdSleepUntil().
Returns:
The system time in ticks.
Function Class:
This is an I-Class API, this function can be invoked from within a system lock zone by both threads and interrupt handlers.
Definition at line 540 of file nil.h.
Referenced by nilSchGoSleepTimeoutS(), and nilTimeNow().
#define nilTimeIsWithin (time, start, end)
Value:
((end) > (start) ? ((time) >= (start)) && ((time) < (end)) :              \
                     ((time) >= (start)) || ((time) < (end)))
Checks if the specified time is within the specified time window.
Note:
When start==end then the function returns always true because the whole time range is specified.
Parameters:
[in] time the time to be verified
[in] start the start of the time window (inclusive)
[in] end the end of the time window (non inclusive)
Return values:
true current time within the specified time window.
false current time not within the specified time window.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 559 of file nil.h.
Referenced by nilSchGoSleepTimeoutS(), and nilTimeNowIsWithin().
#define NIL_THREAD (tname, arg) PORT_THREAD(tname, arg)
Thread declaration macro.
Note:
Thread declarations should be performed using this macro because the port layer could define optimizations for thread functions.
Definition at line 572 of file nil.h.
#define nilDbgAssert (c, m, r)
Value:
{                                             \
  if (!(c)) {                                                               \
    nil.dbg_msg = (m);                                                      \
    nilSysHalt();                                                           \
  }                                                                         \
}
Condition assertion.
If the condition check fails then the kernel panics with the specified message and halts.
Note:
The condition is tested only if the NIL_CFG_ENABLE_ASSERTS switch is specified in nilconf.h else the macro does nothing.
The convention for the message is the following:
<function_name>(), #<assert_number>
The remark string is not currently used except for putting a comment in the code about the assertion.
Parameters:
[in] c the condition to be verified to be true
[in] m the text message
[in] r a remark string
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 593 of file nil.h.
Referenced by _port_thread_start(), nilSchGoSleepTimeoutS(), nilSchReadyI(), nilSemResetI(), nilSemSignalI(), nilSysTimerHandlerI(), nilThdResumeI(), and nilThdSuspendTimeoutS().
#define NIL_IRQ_PROLOGUE () PORT_IRQ_PROLOGUE()
IRQ handler enter code.
Note:
Usually IRQ handlers functions are also declared naked.
On some architectures this macro can be empty.
Function Class:
Special function, this function has special requirements see the notes.
Definition at line 615 of file nil.h.
Referenced by NIL_IRQ_HANDLER().
#define NIL_IRQ_EPILOGUE () PORT_IRQ_EPILOGUE()
IRQ handler exit code.
Note:
Usually IRQ handlers function are also declared naked.
Function Class:
Special function, this function has special requirements see the notes.
Definition at line 623 of file nil.h.
Referenced by NIL_IRQ_HANDLER().
#define NIL_IRQ_HANDLER (id) PORT_IRQ_HANDLER(id)
Standard normal IRQ handler declaration.
Note:
id can be a function name or a vector number depending on the port implementation.
Function Class:
Special function, this function has special requirements see the notes.
Definition at line 632 of file nil.h.
#define NIL_FAST_IRQ_HANDLER (id) PORT_FAST_IRQ_HANDLER(id)
Standard fast IRQ handler declaration.
Note:
id can be a function name or a vector number depending on the port implementation.
Not all architectures support fast interrupts.
Function Class:
Special function, this function has special requirements see the notes.
Definition at line 646 of file nil.h.
#define S2ST (sec) ((systime_t)((sec) * NIL_CFG_FREQUENCY))
Seconds to system ticks.
Converts from seconds to system ticks number.
Note:
The result is rounded upward to the next tick boundary.
Parameters:
[in] sec number of seconds
Returns:
The number of ticks.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 663 of file nil.h.
#define MS2ST (msec)
Value:
((systime_t)(((((uint32_t)(msec)) * ((uint32_t)NIL_CFG_FREQUENCY) - 1UL) /\
                1000UL) + 1UL))
Milliseconds to system ticks.
Converts from milliseconds to system ticks number.
Note:
The result is rounded upward to the next tick boundary.
Parameters:
[in] msec number of milliseconds
Returns:
The number of ticks.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 676 of file nil.h.
#define US2ST (usec)
Value:
((systime_t)(((((uint32_t)(usec)) * ((uint32_t)NIL_CFG_FREQUENCY) - 1UL) /\
                1000000UL) + 1UL))
Microseconds to system ticks.
Converts from microseconds to system ticks number.
Note:
The result is rounded upward to the next tick boundary.
Parameters:
[in] usec number of microseconds
Returns:
The number of ticks.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 690 of file nil.h.
Typedef Documentation
typedef struct port_intctx intctx_t
Type of internal context structure.
Definition at line 201 of file nil.h.
typedef void(* tfunc_t)(void *)
Thread function.
Definition at line 213 of file nil.h.
typedef struct nil_thread_cfg thread_config_t
Type of a structure representing a thread static configuration.
Definition at line 218 of file nil.h.
typedef struct nil_thread thread_t
Type of a structure representing a thread.
Definition at line 223 of file nil.h.
typedef thread_t* thread_ref_t
Type of a thread reference.
Definition at line 239 of file nil.h.