Nil RTOS: NilTimer1
NilTimer1
Detailed Description
Nil RTOS timer 1 functions.
Functions
void nilTimer1Start (uint32_t microseconds)
void nilTimer1Stop ()
bool nilTimer1Wait ()
Defines
#define NIL_TIMER1_VERSION 20130719
Function Documentation
void nilTimer1Start (uint32_t microseconds)
Start periodic timer 1 signals.
Parameters:
[in] microseconds The period in microseconds between signals.
Note:
The maximum value for microseconds is 4,194,304 for a 16 MHz CPU.
Definition at line 61 of file NilTimer1.c.
References nilSysLock, nilSysUnlock, and nilTimer1Stop().
void nilTimer1Stop ()
Stop timer1 signals.
Definition at line 106 of file NilTimer1.c.
Referenced by nilTimer1Start().
bool nilTimer1Wait ()
Sleep while waiting for timer1 signal.
Note:
This function should not be used in the idle thread.
Returns:
true if success or false if overrun or error.
Definition at line 115 of file NilTimer1.c.
References NIL_MSG_TMO, nilIsIdleThread, nilSemWait, nilSemWaitTimeout(), and TIME_IMMEDIATE.
Define Documentation
#define NIL_TIMER1_VERSION 20130719
NilRTimer1 version YYYYMMDD
Definition at line 33 of file NilTimer1.h.